# swagger.yaml
openapi: 3.0.0
info:
  title: API Documentation
  version: 1.0.0
  description: |
    API documentation for Smart house. 
    
    [Collection Postman](https://www.postman.com/dacnpm-5156/workspace/smart-home/request/33929895-d064145f-2819-4285-8321-5f812c4e8690?action=share&creator=33929895&ctx=documentation)

servers:
  - url: http://localhost:3000
    description: Development server



paths:
  /member/register:
    post:
      summary: Đăng ký thành viên mới
      description: Đăng ký thành viên mới với các thông tin cá nhân.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fullname:
                  type: string
                  example: "Nguyễn Văn A"
                email:
                  type: string
                  format: email
                  example: "nguyenvana@example.com"
                phone:
                  type: string
                  example: "0123456789"
                password:
                  type: string
                  format: password
                  example: "secretpassword"
              required:
                - fullname
                - email
                - phone
                - password
      responses:
        "201":
          description: Đăng ký thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Đăng ký thành công!"
                  member:
                    type: object
                    properties:
                      fullname:
                        type: string
                        example: "Nguyễn Văn A"
                      email:
                        type: string
                        example: "nguyenvana@example.com"
                      role:
                        type: string
                        example: "user"
        "400":
          description: Thiếu thông tin hoặc email đã được sử dụng
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Vui lòng nhập đầy đủ thông tin."
        "500":
          description: Lỗi máy chủ khi đăng ký
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Đăng ký thất bại!"

  /voice_recognition_system/add_command:
    post:
      summary: Thêm câu lệnh điều khiển thiết bị
      description: Thêm một câu lệnh mới dùng cho hệ thống nhận diện giọng nói.
      security:
        - bearerAuth: []  # Nếu API cần token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                commandText:
                  type: string
                  example: "Bật đèn phòng khách"
                feed:
                  type: string
                  enum: ["DAT_LED", "DAT_FAN"]
                  example: "DAT_LED"
                payload:
                  type: string
                  enum: ["0", "1", "10", "20", "30", "40"]
                  example: "1"
                actionType:
                  type: string
                  enum: ["onoff", "increase", "decrease"]
                  example: "onoff"
              required:
                - commandText
                - feed
                - payload
      responses:
        "201":
          description: Thêm câu lệnh thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Thêm câu lệnh thành công!"
                  command:
                    type: object
        "400":
          description: Thiếu thông tin đầu vào
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Thiếu thông tin."
        "500":
          description: Lỗi server
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Lỗi khi thêm câu lệnh."
                  error:
                    type: string

  /voice_recognition_system/getCommands:
    get:
      summary: Lấy danh sách câu lệnh
      description: Trả về danh sách các câu lệnh đã lưu trong hệ thống.
      responses:
        "200":
          description: Thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Lấy danh sách câu lệnh thành công!"
                  commands:
                    type: array
                    items:
                      type: object
                      properties:
                        commandText:
                          type: string
                        feed:
                          type: string
                        payload:
                          type: string
                        actionType:
                          type: string
                        createdAt:
                          type: string
                          format: date-time
        "500":
          description: Lỗi server khi lấy câu lệnh
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Lỗi khi lấy danh sách câu lệnh."
                  error:
                    type: string



  /voice_recognition_system/start-recording:
    post:
      summary: Ghi âm và xử lý lệnh giọng nói
      description: Gọi script Python để thu âm từ micro, xử lý đoạn văn bản (transcript), và thực hiện hành động tương ứng.
      responses:
        "200":
          description: Ghi âm thành công và xử lý xong
          content:
            application/json:
              schema:
                type: object
                properties:
                  transcript:
                    type: string
                    example: "Bật đèn phòng khách"
                  message:
                    type: string
                    example: "OK"
        "500":
          description: Lỗi khi xử lý transcript hoặc khi chạy script Python
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid JSON from Python"
